import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
const sidebars: SidebarsConfig = {
    tutorialSidebar: [{type: 'autogenerated', dirName: 'rocketmq'}],
    javaSidebar: [{type: 'autogenerated', dirName: 'java'}],
    redisSidebar: [{type: 'autogenerated', dirName: 'redis'}],
    mysqlSidebar: [{type: 'autogenerated', dirName: 'mysql'}],
    sceneSidebar: [{type: 'autogenerated', dirName: 'scene'}],
    // But you can create a sidebar manually
    // javaSidebar: [
    //   'intro',
    //   'hello',
    //   {
    //     type: 'category',
    //     label: 'Tutorial',
    //     items: ['java/index'],
    //   },
    // ],
};

export default sidebars;
