import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
const sidebars: SidebarsConfig = {
    middlewareSidebar: [{type: 'autogenerated', dirName: 'middleware'}],
    javaSidebar: [{type: 'autogenerated', dirName: 'java'}],
    databaseSidebar: [{type: 'autogenerated', dirName: 'database'}],
    sceneSidebar: [{type: 'autogenerated', dirName: 'scene'}],
    webServerSidebar: [{type: 'autogenerated', dirName: 'web-server'}],
    distributedSidebar: [{type: 'autogenerated', dirName: 'distributed'}],
    microserviceSidebar: [{type: 'autogenerated', dirName: 'microservice'}],
    cloudNativeSidebar: [{type: 'autogenerated', dirName: 'cloudNative'}],
    opensourceSidebar: [{type: 'autogenerated', dirName: 'opensource'}],
    testSidebar: [{type: 'autogenerated', dirName: 'test'}],
    otherSidebar: [{type: 'autogenerated', dirName: 'other'}],
    // But you can create a sidebar manually
    // javaSidebar: [
    //   'intro',
    //   'hello',
    //   {
    //     type: 'category',
    //     label: 'Tutorial',
    //     items: ['java/index'],
    //   },
    // ],
};

export default sidebars;
